### ISSUE TITLE
Example showing exception handling and reconnects

### ISSUE THREAD

**Issue by andrevdm** [hreinhardt/amqp#105]
Would you be interested in a PR showing how to do basic exception handling, channel pooling and connection management?

I think this is something most users of this package would need to do themselves so an example may save some time. I would have liked one :) 

If so I can modify the code from my gist and PR it as an example: https://gist.github.com/andrevdm/a930baa57c10eff5a2b50dce3b9d94d1
(Mostly just the Rabbit.hs file there, and a simplified demo of usage)

Thanks for amqp

**Comment by hreinhardt** [comment]
Sounds great :-)

**Comment by andrevdm** [comment]
Ok great :) 

I'll work on something during the week and send a PR once it it looking reasonable.

Chat shortly then
