### ISSUE TITLE
`fromURI` is partial and can produce confusing errors

### ISSUE THREAD

**Issue by ocharles** [hreinhardt/amqp#110]
I tried to use `fromURI` with `amqp://guest@guest:localhost` and got

```
Prelude.read: no parse
```

I believe the problem is the use of `read` in `fromHostPort`. I think it would be better to use `readMaybe` and remove the partial `read` call.

**Comment by hreinhardt** [comment]
I agree. I've now changed fromURI to return `Either String ConnectionOpts`: https://github.com/hreinhardt/amqp/commit/a67ba32702814a0965fbf23dbe2bbd45fad85489

If the change looks reasonable to you, I can upload it to Hackage.

**Comment by ocharles** [comment]
That was quick! Yes, that looks perfect - I'd be very happy with that. Thanks!

**Comment by hreinhardt** [comment]
New version is on Hackage now 🚀
