### ISSUE TITLE
SSL/TLS Support on Connections

### ISSUE THREAD

**Issue by AlainODea** [hreinhardt/amqp#39]
It would be very useful to have SSL/TLS support.

I was looking at [Network.AMQP.Internal.openConnection''](https://github.com/hreinhardt/amqp/blob/master/Network/AMQP/Internal.hs#L264).  It seems like it should be practical to use [Network.Connection.connectionSetSecure](http://hackage.haskell.org/package/connection-0.1.3/docs/Network-Connection.html#v:connectionSetSecure) to achieve TLS encrypted communications.

Something along the lines of [this answer on StackOverflow](http://stackoverflow.com/questions/11311036/using-tls-extra-for-simple-smtp) may be applicable.

I'll take a crack at this tonight, but I imagine you'll beat me to a working implementation :)

**Comment by woffs** [comment]
Is it possible to have TLS with a client certificate?

**Comment by alain-odea-vgh** [comment]
@woffs not as of now. It's only providing server authentication right now.  The underlying library supports mutual TLS, but I don't expose a method of using it.

**Comment by alain-odea-vgh** [comment]
@woffs what AMQP server are you using that supports mutual TLS? I'd love to have that.

**Comment by woffs** [comment]
just rabbitmq-3.4.3

**Comment by alain-odea-vgh** [comment]
Cool. I did not realize RabbitMQ support that. Thanks :)

**Comment by woffs** [comment]
nb, at the moment, with haskell as client I use
    socat -lm tcp-listen:5672,fork,reuseaddr openssl:amqp-server:5673,verify=0,cert=clientcert.pem
and SASLMechanism "EXTERNAL"

Bit maybe this is just getting off-topic. ;-)

**Comment by woffs** [comment]
Is it possible to expose the TLS method to use a client certificate; or is there a way I could do it by hand? Should I open a new ticket regarding this feature request?

**Comment by AlainODea** [comment]
@woffs **coTLSSettings** does not currently expose the means for doing this:
https://github.com/hreinhardt/amqp/pull/40/commits/a578c1396abf09c92d2c350f79ef5bee8d6b45c0

It only allows toggling TLS server validation on and off.

It should be straight-forward to adapt **TLSSettings**  to include an option for supplying a more complex **Conn.TLSSettings** value:
https://github.com/AlainODea-haskell/amqp/blob/a578c1396abf09c92d2c350f79ef5bee8d6b45c0/Network/AMQP/Internal.hs#L154-163

Broad strokes on this would be:
```haskell
-- | Represents the kind of TLS connection to establish.
data TLSSettings =
    TLSTrusted   -- ^ Require trusted certificates (Recommended).
  | TLSUntrusted -- ^ Allow untrusted certificates (Discouraged. Vulnerable to man-in-the-middle attacks)
  | TLSCustom Conn.TLSSettings -- ^ Provide your own custom TLS settings

connectionTLSSettings :: TLSSettings -> Maybe Conn.TLSSettings
connectionTLSSettings tlsSettings =
  Just $ case tlsSettings of
    TLSTrusted -> Conn.TLSSettingsSimple False False False
    TLSUntrusted -> Conn.TLSSettingsSimple True False False
    TLSCustom x -> x
```

Want to give that a shot?

**Comment by woffs** [comment]
Thanks! I applied that and am trying to get it working. Now I have the problem of constructing a reasonable and working TLSSettings and how to debug. I still get handshake failure and my onCertificateRequest routine don't get called yet. I guess there's no possibility to let TLSSettingsSimple do the work and just add the clientHooks onCertificateRequest?

**Comment by woffs** [comment]
It works! I'll take the freedom to put your suggestion into a PR?

**Comment by AlainODea** [comment]
@woffs that sounds reasonable. I'm not the maintainer. @michaelklishin what do you think?

**Comment by AlainODea** [comment]
Sorry. I meant to tag @hreinhardt.  What do you think of @woffs putting in a PR for exposing full TLS settings customization?  It should be pretty simple.

**Comment by hreinhardt** [comment]
Sounds like a good idea to add this.
