### ISSUE TITLE
availability of reason for connection closing in ConnectionClosedHandler

### ISSUE THREAD

**Issue by woffs** [hreinhardt/amqp#58]
Is there a possibility to get the string of ConnectionClosedException String inside the handler when using addConnectionClosedHandler? Maybe there needs to be another signature for that, with (e -> IO ()) instead of just IO (). Or is there another possibility to get the reason string for closed connections?

**Comment by hreinhardt** [comment]
It's not supported right now. But we have `addChannelExceptionHandler` which gives you the exception for individual channels.

If that doesn't work for you, I agree that it would make sense to add the exception as an additional parameter to the `addConnectionClosedHandler` function.

**Comment by woffs** [comment]
Well, I'm fine with `addChannelExceptionHandler`. :-)
