### ISSUE TITLE
Documentation link in README is broken

### ISSUE THREAD

**Issue by camelpunch** [hreinhardt/amqp#66]
It redirects to https://hackage.haskell.org/package/amqp-0.14.0/docs/Network-AMQP.html, which says, "There is no documentation for amqp-0.14.0. See https://hackage.haskell.org/package/amqp/docs/Network-AMQP.html for the latest version.", which is the original link!

**Comment by hreinhardt** [comment]
This is a bug in Hackage: https://github.com/haskell/hackage-server/issues/478
Easiest solution right now is to just use the Stackage Docs: https://www.stackage.org/nightly/package/amqp

**Comment by camelpunch** [comment]
Thanks!
