### ISSUE TITLE
Channel thread not killed when connection is closed while a subscriber callback is executing

### ISSUE THREAD

**Issue by devwout** [hreinhardt/amqp#69]
When a connection is closed, an exception is thrown in the channel threads, so they are killed. https://github.com/hreinhardt/amqp/blob/master/Network/AMQP/Internal.hs#L285

However, when a subscriber callback is running, this exception gets caught. 
https://github.com/hreinhardt/amqp/blob/master/Network/AMQP/Internal.hs#L546

This means the channel thread will not get killed, and any registered ChannelExceptionHandlers will not get run.

The catching of callback errors should probably be more selective. Should it ignore `ThreadKilled` and `AMQPException`? Or should finaliser errors get tagged and ignored explicitly in the callback catch?

**Comment by hreinhardt** [comment]
I think your idea of ignoring `ThreadKilled` in line 546 should work (I don't think it's likely for an `AMQPException` to be thrown there).

Could you explain what your second approach would look like? Do you want to introduce a new exception that would be thrown instead of `ThreadKilled`? In that case, I believe it would break existing users if their code checks for the `ThreadKilled` exception.

**Comment by devwout** [comment]
It's not just `ThreadKilled` that should be ignored. When the connection gets closed unexpectedly, the exception that came from the `Network.Connections` library will get thrown into the channel thread (line 282). This is indeed not wrapped in an `AMQPException`. So, it's not that easy to detect which exceptions should be re-thrown after running the callback.

My other idea was indeed to introduce a new exception type which wraps the actual exception that is thrown onto the channel thread. When a wrapped exception is caught after executing the callback on line 546, the exception is unwrapped and re-thrown. As you point out, this is indeed incompatible with existing callback client code, as they will observe the wrapped exception now instead of the original one. One could argue if that is a problem, because probably client callback code wasn't expecting to get an exception at random points during the callback anyway.

Alternatively, when a connection gets closed, we can store the exception that closed it in an `IORef` on the connection. The callback catch code can check this variable and re-throw the exception if it is the same. Does not seem like a very pretty solution, but may work.

**Comment by hreinhardt** [comment]
> It's not just ThreadKilled that should be ignored. When the connection gets closed unexpectedly, the exception that came from the Network.Connections library will get thrown into the channel thread (line 282). This is indeed not wrapped in an AMQPException. So, it's not that easy to detect which exceptions should be re-thrown after running the callback.

Oops, you're completely right about this.

> My other idea was indeed to introduce a new exception type which wraps the actual exception that is thrown onto the channel thread. When a wrapped exception is caught after executing the callback on line 546, the exception is unwrapped and re-thrown. As you point out, this is indeed incompatible with existing callback client code, as they will observe the wrapped exception now instead of the original one. One could argue if that is a problem, because probably client callback code wasn't expecting to get an exception at random points during the callback anyway.

I'm not really worried about the callback seeing the wrapped exception, but rather users of `addChannelExceptionHandler`. I could imagine that some users may be checking for `ThreadKilled` there.
We could probably do the unwrapping in the case statement in line 657 to make sure that callers of `addChannelExceptionHandler` keep seeing the same behaviour as today.

> Alternatively, when a connection gets closed, we can store the exception that closed it in an IORef on the connection. The callback catch code can check this variable and re-throw the exception if it is the same. Does not seem like a very pretty solution, but may work.

I agree this doesn't feel very pretty, so I'd lean towards the wrapped-exception approach.

**Comment by devwout** [comment]
I just created a PR using the wrapped exception approach, could you review?
