### ISSUE TITLE
Impossible to create named connections

### ISSUE THREAD

**Issue by kuznero** [hreinhardt/amqp#73]
It seems that it is impossible to create a connection that will show up in RabbitMQ management with a name. Other bindings/libraries allow for that, e.g. RabbitMQ.Client (.Net library). Am I just missing how to do it (cannot find it by reading source code or documentation) or is it missing?

**Comment by michaelklishin** [comment]
It would be easier for the maintainer or contributors to add this if it was explained how it works.
If a connection has a client property `connection_name` set, it will be used in certain log entries as well as management UI, see [e.g. Java client's code](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L931).

This was introduced in RabbitMQ 3.6.3 IIRC.

**Comment by hreinhardt** [comment]
This isn't implemented but I'd be happy to take a patch. If my understanding is correct, you'd need to do this:

- add a field to 'ConnectionOpts' so users can specify the connection-name
- add it to the properties sent to the server when the connection is created: https://github.com/hreinhardt/amqp/blob/094b1f318daf5303c46a4a4f498392338e13c59e/Network/AMQP/Internal.hs#L329

**Comment by kuznero** [comment]
@hreinhardt excellent! thanks for the tip, will try to come up with a PR for it.

**Comment by kuznero** [comment]
@hreinhardt Should be ready, please check if that is ok.

**Comment by hreinhardt** [comment]
Merged. Thanks for contributing. And thanks to @michaelklishin for the additional information.
