### ISSUE TITLE
No Channel.Close_ok sent when channel is closed from server

### ISSUE THREAD

**Issue by frincon** [hreinhardt/amqp#86]
When a soft error from the server is raised, the server sends a Channel.Close message, and expect a Channel.Close_ok response which is not send.

Then, when try to open a new channel with the same connection, the server sent a `CHANNEL_ERROR - second 'channel.open' seen` making the connection to be closed.

According with the documentation (https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf) under section 2.3.7, it is mandatory to return the Channel.Close_ok comand, whether either peer send Channel.Close command.

How to reproduce:
```
#!/usr/bin/env stack
-- stack script --resolver lts-13.26 --package amqp
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
import Network.AMQP
import Control.Exception (catch)
import Control.Concurrent (threadDelay)
import Control.Monad (void)


main :: IO ()
main = do
  conn <- openConnection "127.0.0.1" "/" "guest" "guest"
  chan <- openChannel conn
  confirmSelect chan False

  -- The exchange does not exists, the server send a Channel.close
  publishMsg chan "not-existing-exchange" "" newMsg {msgBody = "some body"}
  threadDelay 1000000
  catch (void $ publishMsg chan "not-existing-exchange" "" newMsg {msgBody = "some body"})
    (\ (_ :: AMQPException) -> return ())

  -- So the channel is closed, open new one
  chan <- openChannel conn
  return ()
```
Expected behavior: Open second channel should not throw an exception. 
Current behavior: The operation fails with `CHANNEL_ERROR - second 'channel.open' seen`

**Comment by frincon** [comment]
Created PR https://github.com/hreinhardt/amqp/pull/87

**Comment by hreinhardt** [comment]
Thanks for the great report and the pull-request!
