### ISSUE TITLE
consumeMessages hangs when committing transaction

### ISSUE THREAD

**Issue by AlexeyRaga** [hreinhardt/amqp#92]
I have this simple consumer:

```haskell
 consumeMsgs chan "ping-queue" Ack $ \(msg, env) -> do
   txSelect chan
   LBS.putStrLn $ msgBody msg
   ackEnv env
   txCommit chan
```

The queue contains a number of messages. 

When I run this program, I see that _only one_ message is being printed to the console. RabbitMQ management console shows that all the messages are in `unacked` state. 

Removing `txCommit` prints all the messages to the console (still unacked, of course).

This makes me think that `txCommit` within `consumeMsgs` doesn't work.

At the same time this code works fine and does not hang after committing a transaction:

```haskell
  msg <- getMsg chan Ack "ping-queue"
  case msg of
    Nothing -> LBS.putStrLn $ "!! NOTHING !!"
    Just (msg, env) -> do
      LBS.putStrLn $ msgBody msg
      ackEnv env
      txCommit chan
```

**Comment by hreinhardt** [comment]
The callback you pass to `consumeMsgs` runs in the event-loop of the AMQP connection. Therefore, if you pass in a blocking function, it will block the whole AMQP connection, leading to a deadlock.

What you could to is to change the callback to a funtion that just stores the incoming messages in some queue-like data-structure and then have a separate thread that processes the messages. This separate thread would safely be able to call blocking functions on the AMQP connection.

**Comment by AlexeyRaga** [comment]
I can try doing that. Although I don't clearly see how transactional semantics would work in this case. Perhaps if instead of a queue I use an `MVar`... But in general, calling `commit` from a separate thread can be very dangerous since you don't really know what you are actually committing...

**Comment by hreinhardt** [comment]
> since you don't really know what you are actually committing...

I'm not sure I'm understanding you correctly, but I don't see how my suggestion would make it harder to see what you are committing. Let's take a more concrete code example of what I would do:

``` haskell

import Control.Concurrent.Chan

main = do
    -- todo: open AMQP connection/channel
    queue <- newChan
    forkIO $ go queue

    consumeMsgs chan "ping-queue" Ack $ \(msg, env) -> do
        writeChan queue (msg, env)
   
go queue = do
    (msg, env) <- readChan queue
    txSelect chan
    -- todo: process the message
    ackEnv env
    txCommit chan
    go queue

``` 

As long as you only have one thread reading from the queue, I don't see how there could be any problems. But maybe I'm missing something.

**Comment by AlexeyRaga** [comment]
Yes, should work for one async thread.
I tried exactly this one but with `MVar` instead of `Chan` (because `Chan` is unbounded), but somehow it is still being blocked somewhere... Trying to figure it out.

**Comment by AlexeyRaga** [comment]
Ah, I have figured the `MVar` thing, that was my fault.

Thanks for the explanation and help!
