### ISSUE TITLE
Design: Exception handling (swallowing?) in subscriber callback.

### ISSUE THREAD

**Issue by alaendle** [hreinhardt/amqp#94]
I'm unhappy with the exception handling of the subscriber callback. Before looking into the code I expected that a unhandled exception gets down to the uncaught exception handler. Since especially in IO a lot of unforeseeable things can happen that just couldn't be handled in a meaningful way by client code (think of out of memory situations).

https://github.com/hreinhardt/amqp/blob/43b0733c9688b22f720f11839301297081fbd10b/Network/AMQP/Internal.hs#L590-L594

But with current design it means that client code need to wrap the subscriber call back with catches - something like:

```haskell
        consumerIdentifier <- AMQP.consumeMsgs ch name AMQP.Ack (\(msg, env) -> do ...
          `CE.catches`
          [
            CE.Handler (\(e::AMQP.ChanThreadKilledException) -> CE.throwIO e),  
            -- need to catch and rethrow
            -- exposes implementation details - why should a client care about ChanThreadKilledException? what if things change?
            CE.Handler (\(e::CE.SomeException) -> 
             -- what next? The subscriber just could do anything useful here by itself!
             -- I see two possibilities here
             -- 1) get the uncaught exception handler and raise it manually (isn't this strange?)
             -- 2) use posix signals to initiate a graceful shutdown
              raiseSignal sigTERM)
          ])
```

All in all this workaround seems unnecessary to me - because if the subscriber callback is able to handle some exceptions in a meaningful way it should do so and no exception will reach your code; if unhandled exceptions occur these should be treated as meant - and not be _silently_ swallowed.

I know this has it's pros and cons and it would be a breaking change to remove the exception handling and it would need some work to ensure proper clean-up, but I really believe it could contribute to more stable clients in the long term. 

And please don't get me wrong - I'm really happy with the AMQP library and appreciate the work of all contributors. I just want to discuss this issue, as at least to me the actual behaviour was unexpected, and so I thought that it might be worth to consider this topic if a major update or redesign of the API happens.

**Comment by hreinhardt** [comment]
I agree that the current approach feels inelegent. Honestly I was expecting most users to have very simple code in the consumeMsgs-callback, so that exception handling would never be an issue.

Regarding your suggested approches:

- "get the uncaught exception handler": What do you mean by 'uncaught exception handler'?

- "use posix signals to initiate a graceful shutdown": You mean shutting down the whole application? To me this feels like overkill and there would probably be people that would be annoyed by this behaviour.

**Comment by alaendle** [comment]
@hreinhardt - Unfortunately I didn't made it perfectly clear that the code in the callback demonstrated just a workaround that might make sense in my application. It's in no way a general approach. The point is that only the client is able to decide what do do, but it might not be possible for the client to do so in the subscriber callback. 

So my preferred approach would be that there is no exception handling necessary at all - just let the channel thread crash (maybe with some clean-up). If there occurs an unhandled exception obviously the client callback code couldn't handle it (which for sure might indicate a bug); but much more important the AMQP library certainly can't. And if the thread simple crashes the uncaught exception handler is executed - which by default just prints the exception to the console (similar to your code) - https://hackage.haskell.org/package/base-4.14.1.0/docs/src/GHC.Conc.Sync.html#uncaughtExceptionHandler.

If things work this way, at least for me, no obscure error handling would be necessary for the client.

```haskell
consumerIdentifier <- AMQP.consumeMsgs ch name AMQP.Ack (\(msg, env) -> do ...
         -- no obscure exception handling necessary here - just catch the exceptions that could be handled here!
         -- other exceptions will crash the channel/consumer thread
         -- and therefore raise the uncaughtExceptionHandler
          )
```

To me this behaviour would be preferable because it's now up to the client to decide how exceptions propagate. The client has the choice to a) make the callback exception-safe by swallowing all exceptions (if this is really what the client wants to do - I doubt this), b) (now the default) unhandled exceptions crash the thread and are printed to console for further inspection, c) install a custom uncaughtExceptionHandler (e.g. to trigger a revamp of the application (e.g. by simply closing and re-establishing the broker connection) or a graceful shutdown).

To take another perspective, what is the advantage for the client if the library swallows exceptions of the callback and prints them out. One useful use might be that this makes it easy to spot such exceptions during debugging/development - since the are shown prominently on the console. But alone this is a double-edged sword - I don't believe that you will recognize the swallowed exceptions (which might hide bugs - just think of partial functions applied to the payload of a message) in production sine the service might continue without interruption and just fail on some messages depending on the payload. So I agree - terminating the application might be overkill - and fore sure this is nothing a library should ever initiate; but just continuing as nothing has happened might even be more dangerous!

Hope I could clarify things a little - hopefully my intention is now more apparent.

 Addendum: To answer your question what I meant by get the uncaught exception handler - but as stated before, this may just be used as a workaround until the library provides a convenient API.
```haskell
consumerIdentifier <- AMQP.consumeMsgs ch name AMQP.Ack (\(msg, env) -> do ...
          `CE.catches`
          [
            CE.Handler (\(e::AMQP.ChanThreadKilledException) -> CE.throwIO e),  
            CE.Handler (\(e::CE.SomeException) -> 
             -- what next? The subscriber just could do anything useful here by itself!
             -- I see two possibilities here
             -- 1) get the uncaught exception handler and raise it manually (isn't this strange?)
              uncaughtEh <- getUncaughtExceptionHandler  -- mimic behaviour of crashed thread by raising the uncaught handler
              uncaughtEh e             
              -- 2) use posix signals to initiate a graceful shutdown
              --raiseSignal sigTERM
              )
          ])
```

**Comment by hreinhardt** [comment]
I don't think the channel should be closed when an exception occurs. What if someone has a long-running program that after a few hours gets a single exception, and suddenly no consumeMsgs-callbacks are executed anymore? That seems worse to me than just skipping the messages that trigger the exception (especially since AMQP is kind of designed for that scenario: if you don't acknowledge the message it will not be removed from the AMQP server).


-----


Now what we theoretically could to would be to add a function like `setUncaughtCallbackExceptionHandler` so the user could provide a callback that would be executed when an exception occurs (I think this would be better than using the existing uncaughtExceptionHandler from GHC). 

But I'm skeptical of whether this is a good idea for two reasons: First, what do we do in the default case? Just print the exception to the screen? In that case, the behaviour would be identical to today.

And second: You could pretty easily achieve something very similar right now if you just code your own wrapper functions for your callbacks:

```haskell
wrapCallback chan action =
    action `CE.catches` [
        CE.Handler (\(e::AMQP.ChanThreadKilledException) -> CE.throwIO e),  
        CE.Handler (\(e::CE.SomeException) -> 
            -- add your preferred way to handle errors here
            forkIO $ closeChannel chan
    ])
    
-- and then whenever you call consumeMsgs:
AMQP.consumeMsgs ch name AMQP.Ack (\(msg, env) -> wrapCallback ch $ doStuff)
```

(The special handling of `AMQP.ChanThreadKilledException` will always be necessary, since we use that internally in the library.)


Another option would be to change `consumeMsgs` so that you would have to provide a separate callback that would handle any exceptions that occur. But I'm also slightly skeptical of this, since - as before - you could easily build something like this yourself by writing a custom `wrapCallback` function.


---

Now don't get me wrong. I agree that the situation isn't really great right now. In a perfect world we'd have a way to specify that the callback may not throw any exception at all, but we don't have that luxury.

**Comment by alaendle** [comment]
@hreinhardt Thanks for your detailed response. I absolutely agree with you that the workaround is simple and everything else requires a breaking change in the libraries API - or at least new capabilities that might make it's usage somehow obscure. So with this in mind it might be the best to just close this issue.

However I still slightly disagree on some points - just from my experience with this issue. At first I wasn't aware of the fact that exceptions got swallowed by the code that raises the subscriber callback - so my naive assumption was that everything works as I've expected (the natural assumption of any programmer). I only noticed the problem after another process (in my case a redis instance) used all available memory and so exceptions occur _"randomly"_ on any IO related code in my haskell program. But I didn't spotted the exceptions directly - and probably I would never have seen them - what I noticed was that the channel from RabbitMQ to the haskell program seems blocked. Just because I limited the prefetchCount to 10 and since exceptions occur no acknowledgement happens, and so the channel gets gradually clogged. As it seems to me the server triggers no redelivery since it believes the channel and connections is OK and the client just needs time to process the delivered messages - which as we know will never happen.

So again, If I need to decide between no exception handling and the swallowing of all exceptions in the subscriber raising code, I still favour the "no exception handling" way - or simple following the advice: Limit error handling to only errors that can actually happen during normal control flow. Crash otherwise.

For me this is simply the more natural way. If anyone needs other behaviour she could easily catch/swallow all exceptions inside the callback (similar to the `wrapCallback` workaround). 

But as stated before I totally understand the weight of status quo, that's why I've ended on the initial report with

> [..] worth to consider this topic if a major update or redesign of the API happens.

**Comment by hreinhardt** [comment]
Thanks for the real-world example. I can see why this would be very annoying.

Honestly, I'm not sure what to do here. I agree that the current behaviour isn't really great, but I also can't come up with an idea that would be a definite improvement, especially if we want to keep backwards-compatibility.

Maybe the best action would be to just make the documentation more clear, i.e. tell users that they should handle any exceptions that may occur?

**Comment by alaendle** [comment]
I absolutely agree. Current behaviour is painful, but it probably doesn't warrant a major change. So a solution via documentation is probably the most reasonable.

Maybe something for the 1.x release backlog 😉

**Comment by hreinhardt** [comment]
Alright, I have added some additional documentation on this behavior.

I think we can close this issue for now; but if anyone has a concrete proposal for improving the implementation, feel free to open a new issue.
